### PR TITLE
Fix selenium auth with firefox

### LINKED ISSUE #945: kindly help with this issue
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Traceback (most recent call last):
  File "C:\Users\Ac\Downloads\OnlyFans-6.4.3\start_ofd.py", line 43, in <module>
    apis = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "C:\Users\Ac\Downloads\OnlyFans-6.4.3\datascraper\main_datascraper.py", line 78, in start_datascraper
    setup, subscriptions = module.account_setup(
  File "C:\Users\Ac\Downloads\OnlyFans-6.4.3\modules\onlyfans.py", line 117, in account_setup
    cookies = oflogin.login(api, domain, proxy)
  File "C:\Users\Ac\Downloads\OnlyFans-6.4.3\extras\OFLogin\start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "C:\Users\Ac\Downloads\OnlyFans-6.4.3\extras\OFLogin\start_ofl.py", line 27, in launch_browser
    opts = webdriver.FirefoxOptions()
AttributeError: module 'seleniumwire.webdriver' has no attribute 'FirefoxOptions'

Everytime its showing this error. kindly please someone guide me

### PR DESCRIPTION
**Pull request by xenon369**
Fixes #945, #952.

from looking at the original error, seleniumwire doesn't expose `FirefoxOptions` or `FirefoxProfile`
https://github.com/wkeeling/selenium-wire/blob/625f545fe331e55fa1696344ecfa5a4a153cfb2b/seleniumwire/webdriver.py

using the suggested methods from selenium seems to work
https://www.selenium.dev/documentation/en/driver_idiosyncrasies/driver_specific_capabilities/#firefox

also i got this working with the latest version of geckodriver so i'm not sure why it's suggested to remain locked in with 0.27.0

### CODE REVIEW

**Comment by DIGITALCRIMINAL** [comment]
Use selenium-wire==2.1.2

**Comment by xenon369** [comment]
2.1.2 works as is cause it was importing everything from selenium
https://github.com/wkeeling/selenium-wire/blob/2.1.2/seleniumwire/webdriver/__init__.py#L1

3.0 restructured their project which no longer does that

the proposed changes will work with either version (2.1.2 or latest)
