### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by IT6uru** [DIGITALCRIMINAL/OnlyFans#1241]
After upgrading to 7.2, I am receiving the following error:

PS Z:\OF\OnlyFans-master> py start_ofd.py
If you're not using >= v7 release, please download said release so the script can properly update your config.
If you're using >= v7 release or you don't care about your current config settings, press enter to continue.

Traceback (most recent call last):
  File "Z:\OF\OnlyFans-master\start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "Z:\OF\OnlyFans-master\tests\main_test.py", line 24, in check_config
    json_config, updated = main_helper.get_config(path)
  File "Z:\OF\OnlyFans-master\helpers\main_helper.py", line 495, in get_config
    json_config = ujson.loads(json.dumps(make_settings.config(
  File "Z:\OF\OnlyFans-master\classes\make_settings.py", line 239, in __init__
    self.settings = Settings(**settings)
  File "Z:\OF\OnlyFans-master\classes\make_settings.py", line 83, in __init__
    self.webhooks = webhooks_settings(settings.get(
  File "Z:\OF\OnlyFans-master\classes\make_settings.py", line 60, in __init__
    self.global_webhooks = option.get(
AttributeError: 'list' object has no attribute 'get'

**Comment by DIGITALCRIMINAL** [comment]
Delete config
