### ISSUE TITLE
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by PanchoBobo** [DIGITALCRIMINAL/OnlyFans#93]
i can run the script on windows bun i cant run it on Linux Mint it trhows thi error 

Traceback (most recent call last):
  File "StartDatascraper.py", line 71, in <module>
    array = x.get_subscriptions(session[0], app_token, session[2])
  File "/home/edgrid/OnlyFans-master/modules/onlyfans.py", line 413, in get_subscriptions
    result_date = datetime.fromisoformat(
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

**Comment by DIGITALCRIMINAL** [comment]
Python version?

**Comment by 2zzen** [comment]
fromisoformat was introduced in 3.7 so ensure that you are using Python >3.7. This should perhaps be included in the docs.

**Comment by PanchoBobo** [comment]
I didnt notice that i was running the python version 3.6. It worked with the version 3.7

**Comment by DIGITALCRIMINAL** [comment]
This script is made with python 3.8.
