### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Mitchwtn** [DIGITALCRIMINAL/OnlyFans#56]
I'm probably doing something wrong on my end, but I'm using linux and this is the error I'm getting, ./StartDatascraper.py: line 2: syntax error near unexpected token `('
./StartDatascraper.py: line 2: `path = os.path.dirname(os.path.realpath(__file__))'

When I run the script it gives me like a cross cursor, and then it takes a screenshot it appears, if that helps.  I believed I followed the instructions correctly but perhaps I'm just inputting something wrong somewhere.

**Comment by DIGITALCRIMINAL** [comment]
Try redownloading StartDatascraper.py

**Comment by Mitchwtn** [comment]
Still does the same thing

**Comment by DIGITALCRIMINAL** [comment]
Are you using Python 3.8?

**Comment by Mitchwtn** [comment]
Thanks, I think that may have been the hang up, I had 3.6.  I installed 3.8, now it's missing the requests module, so I'll have to see if I can figure that out.

**Comment by DIGITALCRIMINAL** [comment]
Did you install the requirements?

**Comment by Mitchwtn** [comment]
Yes, I even got 3.6 farther, but it still errors. `Traceback (most recent call last):
  File "StartDatascraper.py", line 92, in <module>
    session[0], username, site_name, app_token)
  File "/home/michael/Downloads/OnlyFans-master/modules/onlyfans.py", line 56, in start_datascraper
    response = media_scraper(session, site_name, only_links, *item[1])
  File "/home/michael/Downloads/OnlyFans-master/modules/onlyfans.py", line 216, in media_scraper
    offset_array, [session], [media_type], [directory], [username])))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/michael/Downloads/OnlyFans-master/modules/onlyfans.py", line 181, in scrape_array
    date_object = datetime.fromisoformat(media_api["postedAt"])
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
`
When I instruct it to use 3.8 though it's as if it isn't seeing requests on my system.  My only other thought would be that there is no package for win32-setcttime, I don't know if that's just a deal breaker and this script won't work under linux even using python3.8?

**Comment by DIGITALCRIMINAL** [comment]
datetime.datetime doesn't work on 3.6

>https://github.com/DIGITALCRIMINAL/OnlyFans/issues/43
>https://github.com/DIGITALCRIMINAL/OnlyFans/issues/18

For 3.8, try checking that the installed requirements are in the 3.8 site-package folder

**Comment by Mitchwtn** [comment]
Thanks for the nudges, i think I did something wrong when I installed 3.8, so I reinstalled it, it still didn't have requirements or bs4 for 3.8 but this time I had pip3.8 and was able to install them and everything worked fine.
